export const QUESTIONS: Record<number, string> = {
  0: 'O processo seletivo do Programa Aurora busca jovens da região metropolitana de SP, com renda per capita de até 1,5 salários mínimos e que acreditam na educação como ferramenta de mudança. Antes de começarmos queremos saber, você foi indicado por alguém para participar do processo seletivo? Se sim, por favor escreva abaixo o nome completo de quem te indicou.',
  1: 'Antes de começar, queremos saber: você foi indicado(a) por algum(a) jovem que já participou do Aurora para participar deste processo seletivo?',
  2: '1. Nome completo (sem abreviações)',
  3: '2. Nome Social',
  4: '3. CPF',
  5: '4. RG',
  6: '5. E-mail',
  7: '6. Celular com DDD - Incluir apenas números (Exemplo: 11 91234 5678)',
  8: '7. Gênero: Feminino, Masculino, Outro, Prefiro não dizer',
  9: '8. Qual sua cor/raça? Preta, Parda, Amarela, Indígena, Branca',
  10: '9. Você possui algum tipo de deficiência? Sim; Não',
  11: '10. Se sim, qual o tipo de deficiência? Visual; Auditiva; Física; Intelectual; Outro',
  12: '11. Data de nascimento',
  13: '12. Cidade/Estado de nascimento',
  14: '13. Endereço residencial completo ( rua, número, complemento, bairro, CEP )',
  15: '14. Onde você estudou o Ensino Fundamental? Todo em escola pública; Todo em escola particular; Maior parte em escola pública; Maior parte em escola particular; Em outra situação',
  16: '15. Qual nome da sua escola? EE Olga Benatti ; EE Rep. do Paraguay; EE Princesa Isabel; EE. Dr. Kyrillos; EE Carlos Maxmiliano; EE Brisabella ; EE Prof. Lour. Filho; E.E. Dr. R. Ribeiro; Instituto Acaia; Outras.',
  17: '16. Caso tenha preenchido "Outra", digite abaixo o nome da sua escola.',
  18: '17. Sua escola é pública ou privada? (Pública; Privada)',
  19: '18. Você atualmente recebe algum tipo de bolsa escolar? Sim, bolsa por desempenho acadêmico; Sim, bolsa por critério socioeconômico; Não',
  20: '19. Qual série você está cursando? 9º ano Fund. II; Outro',
  21: '20. Em qual período você estuda atualmente? Manhã; Tarde; Integral',
  22: '21. Você já participou de olimpíadas de conhecimento? (Exemplos: OBMEP, OBA, etc) Sim; Não',
  23: '22. Se já participou, quais foram?',
  24: '23. Você faz parte de algum dos projetos abaixo? Se sim, marque qual deles. (Projeto Arrastão; Programadores do Amanhã; LALA; Instituto Arco; Não participo)',
  25: '1. Nome do seu primeiro responsável',
  26: '2. Qual o grau de parentesco de seu primeiro responsável? Mãe/Pai; Avó/Avô; Tio/tia; Outro',
  27: '3. Telefone celular do seu primeiro responsável (DDD + número de telefone. Exemplo: 11912345678 ) - Incluir apenas números',
  28: '4. E-mail do seu primeiro responsável',
  29: '5. Qual é o nível de instrução de seu primeiro responsável? Não estudou; Ensino fundamental; Ensino médio; Ensino superior; Pós-graduação',
  30: '6. Qual é a situação trabalhista atual de seu primeiro responsável? Trabalha com carteira assinada (CLT).; Trabalha de maneira autônoma ou informal.; Desempregado(a).; Aposentado(a).; Pensionista.; Outros.',
  31: '7. Em que seu segundo responsável ou trabalhou, na maior parte da vida? Responda o número da alternativa abaixo: 1. Na indústria.; 2. Na construção civil.; 3. No setor de serviços (comércio, banco, transporte, hotelaria, motorista de aplicativo etc); 4. Funcionária pública do governo federal, estadual ou municipal.; Profissional liberal (por exemplo: dentista, advogado (a), psicólogo (a), etc) , professora ou técnica de nível superior.; 5. Trabalhadora fora de casa em atividades informais (pintora, eletricista, encanadora, feirante, ambulante, guardadora de carros, catadora de lixo etc.).; 6. Trabalha em sua casa em serviços (alfaiataria, cozinha, aulas particulares, artesanato, carpintaria, marcenaria etc).; 7. Trabalhadora doméstica em casa de outras pessoas (faxineira, cozinheira, empregado doméstica, motorista particular, jardineira, vigia, acompanhante de idosos/as etc.); 8. No lar (sem remuneração).; 9. Não trabalha.; 10. Outra opção.; 11. Não sei..',
  32: '8. Nome do seu segundo responsável',
  33: '9. Qual o grau de parentesco de seu segundo responsável? Mãe/Pai; Avó/Avô; Tio/tia; Outro',
  34: '10. Telefone celular do seu segundo responsável (DDD + número de telefone. Exemplo: 11 91234 5678 ) - Incluir apenas números',
  35: '11. E-mail do seu segundo responsável',
  36: '12. Qual é o nível de instrução de seu segundo responsável? Não estudou; Ensino fundamental; Ensino médio; Ensino superior; Pós-graduação',
  37: '13. Qual é a situação trabalhista atual de seu segundo responsável? Trabalha com carteira assinada (CLT).; Trabalha de maneira autônoma ou informal.; Desempregado(a).; Aposentado(a).; Pensionista.; Outros.',
  38: '14. Em que seu segundo responsável ou trabalhou, na maior parte da vida? Responda o número da alternativa abaixo: 1. Na indústria.; 2. Na construção civil.; 3. No setor de serviços (comércio, banco, transporte, hotelaria, motorista de aplicativo etc); 4. Funcionária pública do governo federal, estadual ou municipal.; Profissional liberal (por exemplo: dentista, advogado (a), psicólogo (a), etc) , professora ou técnica de nível superior.; 5. Trabalhadora fora de casa em atividades informais (pintora, eletricista, encanadora, feirante, ambulante, guardadora de carros, catadora de lixo etc.).; 6. Trabalha em sua casa em serviços (alfaiataria, cozinha, aulas particulares, artesanato, carpintaria, marcenaria etc).; 7. Trabalhadora doméstica em casa de outras pessoas (faxineira, cozinheira, empregado doméstica, motorista particular, jardineira, vigia, acompanhante de idosos/as etc.); 8. No lar (sem remuneração).; 9. Não trabalha.; 10. Outra opção.; 11. Não sei.',
  39: '15. Quantas pessoas, além de você, vivem na sua residência? 1; 2; 3; 4; 5 ou mais',
  40: '16. Quantos familiares que moram da sua residência já concluiu o ensino superior? 0; 1, 2; 3,4,5 ou mais ou nenhuma',
  41: '17. Qual é a renda mensal bruta da sua família, somando a renda de todas as pessoas que moram na sua casa? O valor do salário mínimo (SM) é R$ 1.412,00. Até 1 SM - até R$ 1.412,00. ; Acima de 1 até 2 SM - de R$ 1.412,01 até R$ 2.824,00.; Acima de 2 até 3 SM - de R$ 2.824,01 até R$ 4.236,00.; Acima de 3 até 5 SM - de R$ 4.236,01 até R$ 7.060,00.; Acima de 5 até 7 SM - de R$ 7.060,01 até R$ 9.884,00.; Acima de 7 até 10 SM - de R$ 9.884,01 até R$ 14.120,00.; Acima de 10 SM.',
  42: '18. Alguma pessoa que mora com você possui o Cadastro Único (CadÚnico) para Programas Sociais do Governo Federal (CadÚnico)? Sim; Não',
  43: '19. Alguma pessoa que mora com você é beneficiária de programas sociais? Sim; Não',
  44: '20. Quais? Auxílio-Doença; Programa Bolsa Família; BPC; Outros',
  45: '21. Qual a situação do imóvel em que você e sua família residem atualmente? Próprio, quitado.; Cedido por instituição/empresa/parentes/conhecidos.; Próprio, com financiamento em curso.; Alugado.; Próprio, construído em terreno sem regularização.',
  46: '1. No domicílio tem quantos automóveis de passeio exclusivamente para uso particular? Não possui; 1;2;3;4 ou mais',
  47: '2. No domicílio tem quantas máquinas de lavar roupa? Não possui; 1;2;3;4 ou mais',
  48: '3. No domicílio tem quantos banheiros? Não possui; 1;2;3;4 ou mais',
  49: '4. No domicílio tem quantos DVDs? Incluindo qualquer dispositivo que leia DVD e desconsiderando DVD de automóvel Não possui; 1;2;3;4 ou mais',
  50: '5. No domicílio tem quantos freezers independentes ou parte da geladeira duplex? Não possui; 1;2;3;4 ou mais',
  51: '6. No domicílio tem quantos microcomputadores, considerando computadores de mesa, laptops, notebooks e netbooks? Desconsiderar tablets, palms ou smartphones. Não possui; 1;2;3;4 ou mais',
  52: '7. No domicílio tem quantas lavadoras de louça? Não possui; 1;2;3;4 ou mais',
  53: '8. No domicílio tem quantos fornos de micro-ondas? Não possui; 1;2;3;4 ou mais',
  54: '9. No domicílio tem quantas motocicletas, desconsiderando as usadas exclusivamente para uso profissional? Não possui; 1;2;3;4 ou mais',
  55: '10. No domicílio tem quantas máquinas secadoras de roupas, considerando lava e seca? Não possui; 1;2;3;4 ou mais',
  56: '11. Quantos trabalhadores mensalistas vocês possuem na residência, considerando apenas os que trabalham pelo menos cinco dias por semana? Não possui; 1;2;3;4 ou mais',
  57: '12. A água utilizada neste domicílio é proveniente de: Rede geral de distribuição; Poço ou nascente; Outro meio',
  58: '13. Considerando o trecho da rua do seu domicílio, você diria que a rua é: Asfaltada/Pavimentada; Terra/Cascalho',
  59: '1. Você tem preferência pelo online ou presecial? se sim, qual? (caixa de seleção: online / presencial)',
  60: '2. Você tem algum impeditivo para participar do Programa Aurora presencial? se sim, qual? (caixa de seleção: distância / custo do transporte / outro)',
  61: '3. Você tem algum impeditivo para participar do Programa Aurora online? se sim, qual? (caixa de seleção: não tenho dispositivo / não tenho wifi / outro)',
  62: '4. Indique o número que representa as formas de acesso à internet que você utiliza: 1. Wifi em casa. ; 2. Dados próprios.; 3. Wifi de terceiros (escola, trabalho, centros públicos, comércio).; 4. Não acesso a internet..',
  63: '5. Indique os aparelhos que utiliza para acessar a internet: 1. celular; 2. tablet; 3. notebook; 4. não acesso.',
  64: '6. Indique o número de como é o seu acesso a esse(s) aparelho(s): 1. Dos aparelhos assinalados acima, pelo menos um é meu e tenho acesso a ele irrestrito; 2. Dos aparelhos assinalados acima, nenhum deles é meu e preciso solicitar emprestado para alguma das pessoas que residem comigo para usar; 3. Dos aparelhos assinalados acima, nenhum deles é meu e preciso ir a espaços fora de casa (escola ou espaço público) para acessá-los.; 4. Não possuo acesso a nenhum dos aparelhos listados na pergunta acima.',
  65: '7. Indique o número de como é seu espaço de estudos: 1. Possuo um espaço de estudos em que consigo me concentrar, sem necessidade de dividir o ambiente com outras pessoas; 2. Possuo um espaço de estudos em casa que é dividido com outras pessoas (sala, cozinha, etc); 3. Não possuo um espaço de estudos em casa, e preciso ir a outros locais (escola, bilioteca) para conseguir estudar.',
};

