export const QUESTIONS: Record<number, string> = {
  1: 'Antes de começar, queremos saber: você foi indicado(a) por algum(a) jovem que já participou do Aurora para participar deste processo seletivo?',
  2: '1. Nome completo (sem abreviações)',
  3: '2. Qual o seu nome social?',
  4: '3. Envie seu CPF.',
  5: '4. Envie seu RG.',
  6: '5. Qual o seu e-mail?',
  7: '6. Qual o seu celular com DDD?',
  8: '7. Qual o seu gênero?',
  9: '8. Qual a sua cor ou raça?',
  10: '9. Você possuí algum tipo de deficiência?',
  11: '10. Se sim, qual o tipo de deficiência?',
  12: '11. Qual a sua data de nascimento?',
  13: '12. Em qual cidade e estado você nasceu?',
  14: '13. Qual o seu endereço residencial?',
  15: '14. Qual o seu CEP?',
  16: '15. Onde você estudou o Ensino Fundamental?',
  17: '16. Qual nome da sua escola?',
  18: '17. Caso tenha marcado "Outra", envie abaixo o nome da sua escola.',
  19: '18. Sua escola é pública ou particular?',
  20: '19. Você recebe algum tipo de bolsa escolar atualmente?',
  21: '20. Qual série você está cursando?',
  22: '21. Em qual período você estuda atualmente?',
  23: '22. Você já participou de olimpíadas de conhecimento? (Exemplos: OBMEP, OBA, etc)',
  24: '23. Se já participou, quais foram?  (Digite abaixo, caso tenha participado 👇)',
  25: '24. Você faz parte de algum dos projetos abaixo? Se sim, indique qual deles.',
  26: '1. Qual o nome completo do seu primeiro responsável?',
  27: '2. Qual o grau de parentesco de seu primeiro responsável?',
  28: '3. Qual o telefone celular do seu primeiro responsável com DDD?',
  29: '4. Qual o e-mail do seu primeiro responsável?',
  30: '5. Qual é o nível de instrução de seu primeiro responsável?',
  31: '6. Qual é a situação trabalhista atual de seu primeiro responsável?',
  32: '7. Em que seu primeiro responsável trabalha ou trabalhou, na maior parte da vida?',
  33: '8. Qual o nome completo do seu segundo responsável?',
  34: '9. Qual o grau de parentesco de seu segundo responsável?',
  35: '10. Qual o telefone celular do seu segundo responsável com DDD?',
  36: '11. Qual o e-mail do seu segundo responsável?',
  37: '12. Qual é o nível de instrução de seu segundo responsável?',
  38: '13. Qual é a situação trabalhista atual de seu segundo responsável?',
  39: '14. Em que seu segundo responsável trabalha ou trabalhou, na maior parte da vida?',
  40: '15. Quantas pessoas, além de você, vivem na sua residência?',
  41: '16. Quantos familiares que moram da sua residência já concluíram o ensino superior?',
  42: '17. Qual é a renda mensal bruta da sua família, somando a renda de todas as pessoas que moram na sua casa? O valor do salário mínimo (SM) é R$ 1.621,00.',
  43: '18. Alguma pessoa que mora com você possui o Cadastro Único (CadÚnico) para Programas Sociais do Governo Federal (CadÚnico)?',
  44: '19. Alguma pessoa que mora com você é beneficiária de programas sociais?',
  45: '20. Se sim, quais programas sociais?',
  46: '21. Qual a situação do imóvel em que você e sua família residem atualmente?',
  47: '1. No domicílio tem quantos automóveis de passeio exclusivamente para uso particular?',
  48: '2. No domicílio tem quantas máquinas de lavar roupa?',
  49: '3. No domicílio tem quantos banheiros?',
  50: '4. No domicílio tem quantos DVDs? Incluindo qualquer dispositivo que leia DVD e desconsiderando DVD de automóvel.',
  51: '5. No domicílio tem quantos freezers independentes ou parte da geladeira duplex?',
  52: '6. No domicílio tem quantos microcomputadores, considerando computadores de mesa, laptops, notebooks e netbooks? Desconsiderar tablets, palms ou smartphones.',
  53: '7. No domicílio tem quantas lavadoras de louça?',
  54: '8. No domicílio tem quantos  fornos de micro-ondas?',
  55: '9. No domicílio tem quantas motocicletas, desconsiderando as usadas exclusivamente para uso profissional?',
  56: '10. No domicílio tem quantas máquinas secadoras de roupas, considerando lava e seca?',
  57: '11. Quantos trabalhadores mensalistas vocês possuem na residência, considerando apenas os que trabalham pelo menos cinco dias por semana?',
  58: '12. A água utilizada neste domicílio é proveniente de qual meio?',
  59: '13. Considerando o trecho da rua do seu domicílio, como você diria que a sua rua é?',
  60: '1. Você tem preferência pelo Aurora Híbrido ou Aurora Presencial? Se sim, qual?',
  61: '2. Você tem algum impeditivo para participar do Programa Aurora presencial? Se sim, qual?',
  62: '3. Você tem algum impeditivo para participar do Programa Aurora híbrido? Se sim, qual?',
  63: '4. Quais formas de acesso à internet que você utiliza?',
  64: '5. Quais aparelhos você utiliza para acessar a internet?',
  65: '6. Como é o seu acesso a(aos) esse(s) aparalho(s)?',
  66: '7. Como é o seu espaço de estudos?',
  67: 'Envie sua redação, pode ser uma foto legível ou um PDF.',
};
